Ruby Section: Advanced Building Blocks - Enumerable Methods
OA7/Enumerables pull request #1
Opened 2020-04-07 14:32 UTC by OA7

I**n this project, I rebuilt each method in the way I understand the function or method and how they operate.**

- I also added a _test.rb_ file to help run the code in the _enum.rb_ easily and see its functionality.
- To run the code in the _test.rb_ file, make sure to uncomment the code before executing it.

2020-04-07 19:43 UTC, Forison requested changes
## Status:: Require changes🛑
# 🙋‍♂️ team,
You have done a good on this so far, here are a few issues to address to get this project approved.
### 1.```.my_each```, ```.my_each_with_index```, ```my_select```, ```.map```, should return an enumerator when no block is given.
## Check the comment 👇 ‎👇below 👇 ‎👇 and address the issues raised.
### Kindly address the issue below and submit for review
### Happy coding
Addo

2020-04-07 19:43 UTC, Forison commented on enum.rb
> +  def my_all?
### Should have working `my_all?`  identical and returns the same thing as ruby's [`all?`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-all-3F). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_all.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))
``` p %w[ant bear cat].my_all?(/t/) ``` should return same results as ``` p %w[ant bear cat].my_all?(/t/) ```
``` p [1, 2i, 3.14].my_all?(Numeric) ```  should return same results as ``` p [1, 2i, 3.14].all?(Numeric) ```
``` p [nil, true, 99].my_all?```  should return same results as ```p[nil, true, 99].all? ```

2020-04-07 19:43 UTC, Forison commented on enum.rb
> +  def my_any?
###  Should have working `my_any?`  identical and returns the same thing as ruby's [`any?`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-any-3F). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_any.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))
``` p %w[ant bear cat].my_any?(/d/) ``` should return same results as ``` p %w[ant bear cat].any?(/d/) ```
``` p [nil, true, 99].my_any?(Integer)``` should return same results as ```p [nil, true, 99].any?(Integer)```
``` p [nil, true, 99].my_any? ``` shoud return same results as ```p [nil, true, 99].any?(Integer)```
``` p [12,3,34].my_any?(Integer)``` should return same results as ```p [nil, true, 99].any?(Integer)```

2020-04-07 19:43 UTC, Forison commented on enum.rb
> +    new_array = true
### Should have working `my_none?`identical and returns the same thing as ruby's [`none?`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-none-3F). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_none.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))
``` p %w{ant bear cat}.my_none?(/d/)``` should return same results as ``` p %w{ant bear cat}.none?(/d/)```
``` p [1, 3.14, 42].my_none?(Float)``` should return same results as ```[1, 3.14, 42].none?(Float)```
``` p [nil].my_none?``` should return same results as ``` p [nil].none?```
``` p [nil, false].my_none? ``` should return same results as ``` p [nil, false].none? ``` 
``` p [nil, false, true].my_none? ``` should return same results as ``` p [nil, false, true].none? ```

2020-04-07 19:43 UTC, Forison commented on enum.rb
> +    count = 0
###  Should have working `my_count`  identical and returns the same thing as ruby's [`count`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-count). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_count.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))
```ary = [1, 2, 4, 2]```
```p ary.my_count ``` should return same results as ```p ary.count ```
```p ary.my_count{ |x| x%2==0 }``` should return same results as```p ary.count{ |x| x%2==0 }```

2020-04-07 19:43 UTC, Forison commented on enum.rb
> +    mapped = []
### Should have working `my_map` identical and returns the same thing as ruby's [`map`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-map). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_map.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))
``` p [1,2,3,4].map { |li| li*4 } ``` should return same results as ```p [1,2,3,4].map { |li| li*4 }```

2020-04-08 12:44 UTC, stratospherique approved these changes
### Great work implementing the suggested changes :clap: Congrats, the project is approved :heavy_check_mark: You may merge :+1: :+1: 

Keep up the good work :muscle: 
**_Ahmed Mahfoudh_**

2020-04-08 12:59 UTC, merged