Testing Your Ruby Code - Enumerable
OA7/Enumerables pull request #2
Opened 2020-05-01 11:12 UTC by OA7

In this project I wrote code (Rspec), to test the behaviour of my enumerable methods and make sure they perform as intended.

2020-05-01 19:09 UTC, majovanilla requested changes
Hey team!

Great test suite!! You covered almost everything!!

I have just minor requirements before approving your project:

- Check the commented code below and make the necessary changes.

- Try to include more negative test cases. I gave you an example in the comments. But the idea is this: look for edge cases, not the perfect test case. What happens if you give the wrong number of arguments? This will avoid unexpected behaviors in your methods and also in the future applications you build.

## Please, make all REQUIRED changes and submit your request again! 😀

If you have any questions, feel free to send me a message through Slack (@majo)
I would be happy to help! 👩‍💻 

Happy coding 🤓

--Maria Reyes

2020-05-01 19:09 UTC, majovanilla commented on spec/enum_spec.rb
> +
Please use `require_relative` instead of `require`. It is a ruby convention.
Require should be used for external files, like gems, while require_relative should be used for referring to files within your directory.

2020-05-01 19:09 UTC, majovanilla commented on spec/enum_spec.rb
> +  let(:new_array) { [] }
You should include ranges as part of your testing variables.
Some methods behave differently when working with them and you need to make sure they are working! :smiley:

2020-05-01 19:09 UTC, majovanilla commented on spec/enum_spec.rb
> +    end
Please check the negative cases. When the array doesn't include the element you are looking for.

2020-05-04 11:24 UTC, Torres-ssf approved these changes
### Project Approved :muscle: 
Hi there :hand: 
Great job implementing the requested changes :clap: 
Both tests improvements were implemented (testing ranges and negative cases) :tada: 
**This PR is approved**
Good luck with the next project.

Happy coding :computer: 
**Sergio Torres**

2020-05-04 12:35 UTC, merged